# -*- coding: utf-8 -*-
"""KMeansClustering_on_Mall_Customers_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CU5P_1dUybXyrhI0Drwkpr_rww4u7Qyd
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data=pd.read_csv('/content/drive/MyDrive/Mall_Customers.csv')

data.info()

x=data[['Annual Income (k$)','Spending Score (1-100)']]

from sklearn.cluster import KMeans
wcss=[]
for i in range(1,11):
  kmeans=KMeans(n_clusters=i,init='k-means++')
  kmeans.fit(x)
  wcss.append(kmeans.inertia_)

plt.plot(range(1,11),wcss)

kmeans = KMeans(n_clusters=5, init='k-means++', random_state=0)
labels = kmeans.fit_predict(x)

kmeans.inertia_

kmeans.labels_

print(x.shape)

plt.figure(figsize=(15, 7))

plt.scatter(x.iloc[labels == 0, 0], x.iloc[labels == 0, 1], color='yellow', label='Cluster 1', s=50)
plt.scatter(x.iloc[labels == 1, 0], x.iloc[labels == 1, 1], color='blue', label='Cluster 2', s=50)
plt.scatter(x.iloc[labels == 2, 0], x.iloc[labels == 2, 1], color='green', label='Cluster 3', s=50)
plt.scatter(x.iloc[labels == 3, 0], x.iloc[labels == 3, 1], color='cyan', label='Cluster 4', s=50)
plt.scatter(x.iloc[labels == 4, 0], x.iloc[labels == 4, 1], color='magenta', label='Cluster 5', s=50)

plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:, 1], s=200, c='red', marker='X', label='Centroids')

plt.title('KMeans Clustering with 5 Clusters')
plt.xlabel('Feature 1')
plt.ylabel('Feature 2')
plt.legend()
plt.grid(True)
plt.show()

